name: Build and Test

on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: 'Build'
      run: dotnet build './examples/n8n.SDK.ConsoleApp/n8n.SDK.ConsoleApp.csproj' -c Release